ELK_LOGSTASH_PASS: Changeme_123
ELK_ADMIN_PASS: Changeme_123
LADP_DIND_DN_PASSWD: Changeme_123


binaries_mirror: "https://download.aiziyuer.familyds.com:5001/blob/sha256sum"

binaries:
  centos:
    name: CentOS.iso
    versions:
      "7":
        sha256sum: "e33d7b1ea7a9e2f38c8f693215dd85254c3a4fe446f93f563279715b68d07987"
        url: "https://mirrors.aliyun.com/centos/7/isos/x86_64/CentOS-7-x86_64-DVD-2009.iso"

