---
- name: ensures etcd dirs
  file: path={{ item }} state=directory
  with_items:
    - /etc/systemd/system

- name: copy files
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode | default('0644')}}
  with_items:
    - { src: logstash.conf, dest: "/etc/logstash/conf.d/logstash.conf" }
    - { src: logstash.service, dest: "/etc/systemd/system/logstash.service" }

- name: restart service
  systemd:
    name: logstash
    daemon_reload: yes
    state: restarted
    enabled: yes
