---
- name: ensures etcd dirs
  file: path={{ item }} state=directory
  with_items:
    - /tmp/repository/
    - ~/iso
    - ~/CentOS7-OS_x86_64/MY-PXE

- name: download all
  shell: |
    while echo '{{ item.sha256sum }} {{ item.dest }}' | sha256sum --check --status &>/dev/null; [ $? -ne 0 ]; do 
        curl -sSL {{ binaries_mirror }}/{{ item.sha256sum }} -o {{ item.dest }} || curl -sSL {{ item.url }} -o {{ item.dest }}; 
    done
  with_items:
    - {
        dest: "/tmp/repository/{{ binaries['centos']['name'] }}",
        sha256sum: "{{ binaries['centos']['versions']['7']['sha256sum'] }}",
        url: "{{ binaries['centos']['versions']['7']['url'] }}",
      }

- name: unarchive iso
  shell: |
    umount ~/iso || true
    mkdir -p ~/iso
    mount /tmp/repository/CentOS.iso ~/iso
    rsync -avz /usr/share/syslinux/ ~/CentOS7-OS_x86_64/MY-PXE/

- name: create ks
  shell: |
    cat <<'EOF'>~/CentOS7-OS_x86_64/MY-PXE/ks.cfg
    lang en_US
    keyboard us
    timezone America/New_York --isUtc
    rootpw $1$2Xb7M2dX$TwMDmYgnlGhfiCMYU9xww1 --iscrypted
    #platform x86, AMD64, or Intel EM64T
    reboot
    text
    url --url=http://10.10.10.114:30003/mirror.centos.org/os/x86_64
    bootloader --location=mbr --append="rhgb quiet crashkernel=auto"
    zerombr
    clearpart --all --initlabel
    autopart
    auth --passalgo=sha512 --useshadow
    selinux --permissive
    firewall --disabled
    skipx
    firstboot --disable
    %packages
    @^minimal  
    @core  
    chrony  
    kexec-tools 
    %end
    EOF

- name: create pxelinux.cfg
  shell: |
    mkdir -p ~/CentOS7-OS_x86_64/MY-PXE/pxelinux.cfg
    cp ~/CentOS7-OS_x86_64/ ~/CentOS7-OS_x86_64/MY-PXE
    cp -pv ~/iso/images/pxeboot/{initrd.img,vmlinuz} ~/CentOS7-OS_x86_64/MY-PXE
    cat <<'EOF'>~/CentOS7-OS_x86_64/MY-PXE/pxelinux.cfg/default
    default menu.c32
    prompt 0
    timeout 30
    menu title Homelab PXE Menu
    label Install CentOS 7 Server
      kernel /vmlinuz
      append initrd=/initrd.img ip=dhcp method=http://10.10.10.114:30003/mirror.centos.org/os/x86_64 devfs=nomount inst.repo=http://10.10.10.114:30003/mirror.centos.org/os/x86_64 inst.ks=http://10.10.10.114:30003/mirror.centos.org/os/x86_64/MY-PXE/ks.cfg
    EOF

- name: rsync...
  shell: |
    rsync -avz ~/iso/ moyi@10.10.10.114:/volume1/docker/download.aiziyuer.familyds.com/data/mirror.centos.org/os/x86_64/
    rsync -avz ~/CentOS7-OS_x86_64/ moyi@10.10.10.114:/volume1/docker/download.aiziyuer.familyds.com/data/mirror.centos.org/os/x86_64/



