---
- name: ensures dirs
  file: path={{ item }} state=directory
  with_items:
    - /tmp/repository/
    - ~/iso

- name: download all
  shell: |
    while echo '{{ item.sha256sum }} {{ item.dest }}' | sha256sum --check --status &>/dev/null; [ $? -ne 0 ]; do 
        curl -sSL {{ binaries_mirror }}/{{ item.sha256sum }} -o {{ item.dest }} || curl -sSL {{ item.url }} -o {{ item.dest }}; 
    done
  with_items:
    - {
        dest: "/tmp/repository/{{ binaries['centos']['name'] }}",
        sha256sum: "{{ binaries['centos']['versions']['7']['sha256sum'] }}",
        url: "{{ binaries['centos']['versions']['7']['url'] }}",
      }

- name: ensures dirs for templates
  file:
    path: "{{ item.path | dirname }}"
    state: directory
    recurse: yes
  with_filetree:
    - "../templates/"
    - "../files/"
  when: item.state == 'file'

- name: sync file for tempaltes
  template: src={{ item.src }} dest="~/{{ item.path | regex_replace('\.j2$', '') }}" 
  with_filetree:
    - "../templates/"
  when: item.state == 'file'

- name: sync file files
  copy: src={{ item.src }} dest="~/{{ item.path }}" 
  with_filetree:
    - "../templates/"
  when: item.state == 'file'

- name: copy centos7 os
  shell: |
    umount ~/iso || true
    mount /tmp/repository/CentOS.iso ~/iso || true
    cp -pv ~/iso/images/pxeboot/{initrd.img,vmlinuz} ~/PXE-BOOT/os/centos7

- name: rsync...
  shell: |
    rsync -avz ~/iso/ moyi@10.10.10.114:/volume1/docker/download.aiziyuer.familyds.com/data/mirror.centos.org/os/x86_64/
    rsync -avz ~/PXE-BOOT moyi@10.10.10.114:/volume1/public/



