---
- name: ensures etcd dirs
  file: path={{ item }} state=directory
  with_items:
    - /tmp/repository/
    - ~/iso
    - ~/CentOS7-OS_x86_64/MY-PXE

- name: download all
  shell: |
    while echo '{{ item.sha256sum }} {{ item.dest }}' | sha256sum --check --status &>/dev/null; [ $? -ne 0 ]; do 
        curl -sSL {{ binaries_mirror }}/{{ item.sha256sum }} -o {{ item.dest }} || curl -sSL {{ item.url }} -o {{ item.dest }}; 
    done
  with_items:
    - {
        dest: "/tmp/repository/{{ binaries['centos']['name'] }}",
        sha256sum: "{{ binaries['centos']['versions']['7']['sha256sum'] }}",
        url: "{{ binaries['centos']['versions']['7']['url'] }}",
      }

- name: unarchive iso
  shell: |
    mkdir -p ~/iso 
    mount /tmp/repository/CentOS.iso ~/iso
    rsync -avz ~/iso/ ~/CentOS7-OS_x86_64/
    umount ~/iso
    rsync -avz /usr/share/syslinux/ ~/CentOS7-OS_x86_64/MY-PXE/

- name: create ks
  shell: |
    cat <<'EOF'>~/CentOS7-OS_x86_64/MY-PXE/ks.cfg
    #version=DEVEL
    # System authorization information
    auth --enableshadow --passalgo=sha512
    # Use CDROM installation media
    cdrom
    # Use graphical install
    text
    # Run the Setup Agent on first boot
    firstboot --enable
    ignoredisk --only-use=sda
    # Keyboard layouts
    keyboard --vckeymap=us --xlayouts='us'
    # System language
    lang en_US.UTF-8

    # Network information
    network  --bootproto=dhcp --onboot=on --noipv6 --no-activate
    network  --hostname=localhost.localdomain

    # Root password
    rootpw --iscrypted $6$AN4MBBii5LT4V4z5$zqGKKz1fBqZxNAc3ltbOzlz.8f/gjttgNEAsUiA6TTh2fI3cEvGZszlQq7GC3ItgLpnodkKHDLS5zuEoGbKfX0
    # System services
    services --enabled="chronyd"
    # System timezone
    timezone America/New_York --isUtc
    # System bootloader configuration
    bootloader --append=" crashkernel=auto" --location=mbr --boot-drive=sda
    # Partition clearing information
    clearpart --none --initlabel
    # Disk partitioning information
    part pv.156 --fstype="lvmpv" --ondisk=sda --size=15359
    part /boot --fstype="xfs" --ondisk=sda --size=1024
    volgroup centos --pesize=4096 pv.156
    logvol /  --fstype="xfs" --grow --maxsize=51200 --size=1024 --name=root --vgname=centos
    logvol swap  --fstype="swap" --size=1638 --name=swap --vgname=centos

    %packages
    @^minimal
    @core
    chrony
    kexec-tools

    %end

    %addon com_redhat_kdump --enable --reserve-mb='auto'

    %end

    %anaconda
    pwpolicy root --minlen=6 --minquality=1 --notstrict --nochanges --notempty
    pwpolicy user --minlen=6 --minquality=1 --notstrict --nochanges --emptyok
    pwpolicy luks --minlen=6 --minquality=1 --notstrict --nochanges --notempty
    %end
    EOF

- name: create pxelinux.cfg
  shell: |
    mkdir -p ~/CentOS7-OS_x86_64/MY-PXE/pxelinux.cfg
    cp ~/CentOS7-OS_x86_64/ ~/CentOS7-OS_x86_64/MY-PXE
    cp -pv ~/CentOS7-OS_x86_64/images/pxeboot/{initrd.img,vmlinuz} ~/CentOS7-OS_x86_64/MY-PXE
    cat <<'EOF'>~/CentOS7-OS_x86_64/MY-PXE/pxelinux.cfg/default
    default menu.c32
    prompt 0
    timeout 30
    menu title Homelab PXE Menu
    label Install CentOS 7 Server
      kernel /vmlinuz
      append initrd=/initrd.img inst.repo=10.10.10.114:30003/mirror.centos.org/os/x86_64/ ks=10.10.10.114:30003/mirror.centos.org/os/x86_64/MY-PXE/ks.cfg
    EOF

- name: rsync...
  shell: |
    rsync -avz ~/CentOS7-OS_x86_64/ moyi@10.10.10.114:/volume1/docker/download.aiziyuer.familyds.com/data/mirror.centos.org/os/x86_64/



