---

# /public 是nfs映射了远程pxe的文件服务器/public目录

- name: ensures dirs
  file: path={{ item }} state=directory
  with_items:
    - /public/repository/
    - ~/iso

- name: download all
  shell: |
    while echo '{{ item.sha256sum }} {{ item.dest }}' | sha256sum --check --status &>/dev/null; [ $? -ne 0 ]; do 
        curl -sSLf {{ binaries_mirror }}/{{ item.sha256sum }} -o {{ item.dest }} || curl -sSLf {{ item.url }} -o {{ item.dest }}; 
    done
  with_items:
    - {
        dest: "/public/repository/{{ binaries['centos']['versions']['7']['name'] | default(binaries['centos']['name']) }}",
        sha256sum: "{{ binaries['centos']['versions']['7']['sha256sum'] }}",
        url: "{{ binaries['centos']['versions']['7']['url'] }}",
      }
    - {
        dest: "/public/repository/{{ binaries['euler']['versions']['2.2']['name'] | default(binaries['euler']['name']) }}",
        sha256sum: "{{ binaries['euler']['versions']['2.2']['sha256sum'] }}",
        url: "{{ binaries['euler']['versions']['2.2']['url'] }}",
      }
  tags:
    - dev

- name: ensures dirs for templates
  file:
    path: "/public/{{ item.path | dirname }}"
    state: directory
    recurse: yes
  with_filetree:
    - "../templates/"
    - "../files/"
  when: item.state == 'file'

- name: sync file for tempaltes
  template: src={{ item.src }} dest="/public/{{ item.path | regex_replace('\.j2$', '') }}"
  with_filetree:
    - "../templates/"
  when: item.state == 'file'

- name: sync file files
  copy: src={{ item.src }} dest="/public/{{ item.path }}"
  with_filetree:
    - "../files/"
  when: item.state == 'file'

- name: make os
  shell: |
    umount ~/iso || true
    mount /public/repository/{{ item }} ~/iso || true
    cp -pv ~/iso/images/pxeboot/{initrd.img,vmlinuz} /public/PXE-BOOT/os/{{ item | regex_replace('\.iso$', '') }}
    mkdir -p /public/{{ item | regex_replace('\.iso$', '') }}
    rsync -avz ~/iso/ /public/{{ item | regex_replace('\.iso$', '') }}/
    umount ~/iso
  with_items:
    - "{{ binaries['centos']['versions']['7']['name'] | default(binaries['centos']['name']) }}"
    - "{{ binaries['euler']['versions']['2.2']['name'] | default(binaries['euler']['name']) }}"

