---

binaries:
  centos:
    name: centos.iso
    versions:
      "7":
        name: centos7.iso
        sha256sum: "e33d7b1ea7a9e2f38c8f693215dd85254c3a4fe446f93f563279715b68d07987"
        url: "https://mirrors.aliyun.com/centos/7/isos/x86_64/CentOS-7-x86_64-DVD-2009.iso"
  euler:
    name: euler.iso
    versions:
      "2.2":
        name: euler2sp2.iso
        sha256sum: "173291aa3ed7fc5de5e8a2bc0ac9d81d644de7b0e76d6e90099badc986b2fe81"
        url: "https://repo.huaweicloud.com/euler/2.2/os/x86_64/iso/20170930/EulerOS-V2.0SP2-x86_64-dvd.iso"
