---
- name: ensures etcd dirs
  file: path={{ item }} state=directory
  with_items:
    - /etc/systemd/system

# kuberntes不允许主机名出现下划线
- name: change hostname
  shell: |
    hostnamectl set-hostname "{{ inventory_hostname | replace("_", "-") }}"

- name: turn off selinux
  selinux:
    state: disabled
  ignore_errors: True

- name: stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: False
  ignore_errors: True

- name: disable ipv6 by sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  when:
    - disable_ipv6 | default('true') | bool
  with_items:
    - { name: "net.ipv6.conf.all.disable_ipv6", value: "1" }
    - { name: "net.ipv6.conf.default.disable_ipv6", value: "1" }
    - { name: "net.ipv6.conf.lo.disable_ipv6", value: "1" }

- name: install pakcage
  apt:
    pkg:
      - elasticsearch

- name: copy templates
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode | default('0644')}}
  with_items:
    - {
        src: elasticsearch.yml.j2,
        dest: "/etc/elasticsearch/elasticsearch.yml",
      }
    - { src: role_mapping.yml, dest: "/etc/elasticsearch/role_mapping.yml" }
    - { src: roles.yml, dest: "/etc/elasticsearch/roles.yml" }

- name: copy files
  copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode | default('0644')}}
  with_items:
    - {
        src: x-pack-core-7.12.0.jar,
        dest: "/usr/share/elasticsearch/modules/x-pack-core/x-pack-core-7.12.0.jar",
      }

- name: restart service
  systemd:
    name: elasticsearch
    daemon_reload: yes
    state: restarted
    enabled: yes
