# Role mapping configuration file which has elasticsearch roles as keys
# that map to one or more user or group distinguished names

#roleA:   this is an elasticsearch role
#  - groupA-DN  this is a group distinguished name
#  - groupB-DN
#  - user1-DN   this is the full user distinguished name

superuser:
  - "cn=home-admin,cn=groups,dc=aiziyuer,dc=familyds,dc=com"

monitoring:
  - "cn=home-admin,cn=groups,dc=aiziyuer,dc=familyds,dc=com"
  - "cn=users,cn=groups,dc=aiziyuer,dc=familyds,dc=com"

user:
  - "cn=users,cn=groups,dc=aiziyuer,dc=familyds,dc=com"
  - "cn=home-admin,cn=groups,dc=aiziyuer,dc=familyds,dc=com"
