# Role mapping configuration file which has elasticsearch roles as keys
# that map to one or more user or group distinguished names

#roleA:   this is an elasticsearch role
#  - groupA-DN  this is a group distinguished name
#  - groupB-DN
#  - user1-DN   this is the full user distinguished name

superuser:
{% for group in LADAP_ADMIN_GROUPS %}
  - "{{ group }}"
{% endfor %}

monitoring:
{% for group in LADAP_ADMIN_GROUPS %}
  - "{{ group }}"
{% endfor %}
{% for group in LDAP_USER_GROUPS %}
  - "{{ group }}"
{% endfor %}

logstash_writer:
  - uid=elk-logstash,cn=users,dc=aiziyuer,dc=familyds,dc=com
