logstash_writer:
  cluster:
    - "manage_index_templates"
    - "monitor"
    - "manage_ilm"
  indices:
    - names:
        - "logstash-*"
      privileges:
        - "write"
        - "create"
        - "delete"
        - "create_index"
        - "manage"
        - "manage_ilm"
      allow_restricted_indices: false
  applications: []
  run_as: []
  metadata:
    _reserved: true
  transient_metadata:
    enabled: true
